#                   __ _                                          _       
#   ___ ___  _ __  / _(_) __ _ _   _ _ __ ___       ___ _   _  __| | ___  
#  / __/ _ \| '_ \| |_| |/ _` | | | | '__/ _ \_____/ __| | | |/ _` |/ _ \ 
# | (_| (_) | | | |  _| | (_| | |_| | | |  __/_____\__ \ |_| | (_| | (_) |
#  \___\___/|_| |_|_| |_|\__, |\__,_|_|  \___|     |___/\__,_|\__,_|\___/ 
#                        |___/                                            
- hosts: all
  become: true
  become_user: root
  remote_user: root
  tasks:
    - name: configure-sudo | wheel group should be created
      register: wheel
      changed_when: wheel.rc > 0
      ignore_errors: true
      shell: grep '^wheel:' /etc/group 2> /dev/null

    - name: configure-sudo | wheel group should be created
      when: wheel|failed
      group:
        name:   "wheel"
        system: "yes"
        state:  "present"

    - name: configure-sudo | root should be included in wheel group
      ignore_errors: true
      user:
        name:   "root"
        groups: "wheel"

    # --------------------------------------------------------------------------
    - block:
        - name: configure-sudo | RedHat | sudo(8) should be installed
          yum:
            name:  "sudo"
            state: "present"

        - name: configure-sudo | RedHat | Enable sudo for users in wheel group
          replace:
            backup:  "yes"
            dest:    "/etc/sudoers"
            regexp:  '^# %wheel\s+ALL=\(ALL\)\s+ALL$'
            replace: '%wheel	ALL=(ALL)	ALL'
      when: ansible_os_family == "RedHat"

    # --------------------------------------------------------------------------
    - block:
        - name: configure-sudo | Debian | sudo(8) should be installed
          apt:
            name:  "sudo"
            state: "present"
      when: ansible_os_family == "Debian"

    # --------------------------------------------------------------------------
    - block:
        - name: configure-sudo | FreeBSD | sudo(8) should be installed
          pkgng:
            name:  "sudo"
            state: "present"

        - name: configure-sudo | FreeBSD | Enable sudo for users in wheel group
          replace:
            backup:  "yes"
            dest:    "/usr/local/etc/sudoers"
            regexp:  '^# %wheel\s+ALL=\(ALL\)\s+ALL$'
            replace: '%wheel ALL=(ALL) ALL'
      when: ansible_os_family == "FreeBSD"

    # --------------------------------------------------------------------------
    - block:
        - name: configure-sudo | OpenBSD | Enable sudo for users in wheel group
          replace:
            backup:  "yes"
            dest:    "/etc/sudoers"
            regexp:  '^# %wheel\s+ALL=\(ALL\)\s+SETENV:\s+ALL$'
            replace: '%wheel        ALL=(ALL) SETENV: ALL'
      when: ansible_os_family == "OpenBSD"

